export default {
  cn: { name: "中国人", short: "中国人", iso: "cn" },
  cz: { name: "Čeština", short: "Češ", iso: "cz" },
  de: { name: "Deutsch", short: "Deu", iso: "de" },
  es: { name: "Español", short: "Esp", iso: "es" },
  fr: { name: "Français", short: "Fra", iso: "fr" },
  gb: { name: "English (GB)", short: "Eng", iso: "gb" },
  gr: { name: "Ελληνικά", short: "Ελλ", iso: "gr" },
  he: { name: "עברית", short: "עבר", iso: "il" },
  hr: { name: "Hrvatski", short: "Hrv", iso: "hr" },
  id: { name: "Indonesia", short: "Ind", iso: "id" },
  in: { name: "हिंदी", short: "हिंदी", iso: "in" },
  it: { name: "Italiano", short: "Ita", iso: "it" },
  jp: { name: "日本語", short: "日本語", iso: "jp" },
  nl: { name: "Nederlands", short: "Ned", iso: "nl" },
  pk: { name: "اردو", short: "ارد", iso: "pk" },
  pt: { name: "Português", short: "Por", iso: "pt" },
  ru: { name: "Русский", short: "Рус", iso: "ru" },
  th: { name: "ภาษาไทย", short: "ภาษ", iso: "th" },
  tr: { name: "Türkçe", short: "Tür", iso: "tr" },
  tz: { name: "Kiswahili", short: "Kis", iso: "tz" },
  us: { name: "English (US)", short: "Eng", iso: "us" },
  vn: { name: "Tiếng Việt", short: "Việ", iso: "vn" },
}
