export enum MessageTypes {
  SIGN_DATA = 'SIGN_DATA',
  SIGN_TX = 'SIGN_TX',
  SUBMIT_TX = 'SUBMIT_TX',
  VERIFY_SPENDING_PASSWORD = 'VERIFY_SPENDING_PASSWORD',
  SIGN_WITH_GOOGLE = 'SIGN_WITH_GOOGLE',
  ACTIVATE_GOOGLE_WALLET = 'ACTIVATE_GOOGLE_WALLET',
  RESTORE = 'RESTORE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  RESYNC = 'RESYNC',
  CONNECT_TREZOR = 'CONNECT_TREZOR',
  REMOVE_PENDING_TRANSACTION = 'REMOVE_PENDING_TRANSACTION',
}
