export enum MessageTypes {
  CREATE_NEW_WALLET = 'CREATE_NEW_WALLET',
  CREATE_NEW_HARDWARE_WALLET = 'CREATE_NEW_HARDWARE_WALLET',
  SIGN_TX = 'SIGN_TX',
  SUBMIT_TX = 'SUBMIT_TX',
  VERIFY_SPENDING_PASSWORD = 'VERIFY_SPENDING_PASSWORD',
  SIGN_WITH_GOOGLE = 'SIGN_WITH_GOOGLE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  RESYNC = 'RESYNC',
}
