export enum MessageTypes {
  SIGN_DATA = 'SIGN_DATA',
  SIGN_TX = 'SIGN_TX',
  SUBMIT_TX = 'SUBMIT_TX',
  VERIFY_SPENDING_PASSWORD = 'VERIFY_SPENDING_PASSWORD',
  SIGN_WITH_GOOGLE = 'SIGN_WITH_GOOGLE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  RESYNC = 'RESYNC',
}
